#############################################################################
# Makefile for building: qt-material-widgets
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  qt-material-widgets.pro
# Template: subdirs
# Command: /usr/bin/qmake6 -o Makefile qt-material-widgets.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qt-material-widgets1.0.0
DISTDIR = /home/runner/work/qt-material-widgets/qt-material-widgets/.tmp/qt-material-widgets1.0.0
SUBTARGETS    =  \
		sub-components \
		sub-examples


sub-components-qmake_all:  FORCE
	@test -d components/ || mkdir -p components/
	cd components/ && $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/components/components.pro
	cd components/ && $(MAKE) -f Makefile qmake_all
sub-components: FORCE
	@test -d components/ || mkdir -p components/
	cd components/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/components/components.pro ) && $(MAKE) -f Makefile
sub-components-make_first: FORCE
	@test -d components/ || mkdir -p components/
	cd components/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/components/components.pro ) && $(MAKE) -f Makefile 
sub-components-all: FORCE
	@test -d components/ || mkdir -p components/
	cd components/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/components/components.pro ) && $(MAKE) -f Makefile all
sub-components-clean: FORCE
	@test -d components/ || mkdir -p components/
	cd components/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/components/components.pro ) && $(MAKE) -f Makefile clean
sub-components-distclean: FORCE
	@test -d components/ || mkdir -p components/
	cd components/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/components/components.pro ) && $(MAKE) -f Makefile distclean
sub-components-install_subtargets: FORCE
	@test -d components/ || mkdir -p components/
	cd components/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/components/components.pro ) && $(MAKE) -f Makefile install
sub-components-uninstall_subtargets: FORCE
	@test -d components/ || mkdir -p components/
	cd components/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/components/components.pro ) && $(MAKE) -f Makefile uninstall
sub-examples-qmake_all:  FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/examples/examples.pro
	cd examples/ && $(MAKE) -f Makefile qmake_all
sub-examples: FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/examples/examples.pro ) && $(MAKE) -f Makefile
sub-examples-make_first: FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/examples/examples.pro ) && $(MAKE) -f Makefile 
sub-examples-all: FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/examples/examples.pro ) && $(MAKE) -f Makefile all
sub-examples-clean: FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/examples/examples.pro ) && $(MAKE) -f Makefile clean
sub-examples-distclean: FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/examples/examples.pro ) && $(MAKE) -f Makefile distclean
sub-examples-install_subtargets: FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/examples/examples.pro ) && $(MAKE) -f Makefile install
sub-examples-uninstall_subtargets: FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/examples/examples.pro ) && $(MAKE) -f Makefile uninstall

Makefile: qt-material-widgets.pro .qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		qt-material-widgets.pro
	$(QMAKE) -o Makefile qt-material-widgets.pro
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
qt-material-widgets.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile qt-material-widgets.pro

qmake_all: sub-components-qmake_all sub-examples-qmake_all FORCE

make_first: sub-components-make_first sub-examples-make_first  FORCE
all: sub-components-all sub-examples-all  FORCE
clean: sub-components-clean sub-examples-clean  FORCE
distclean: sub-components-distclean sub-examples-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-components-install_subtargets sub-examples-install_subtargets FORCE
uninstall_subtargets: sub-components-uninstall_subtargets sub-examples-uninstall_subtargets FORCE

sub-components-check:
	@test -d components/ || mkdir -p components/
	cd components/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/components/components.pro ) && $(MAKE) -f Makefile check
sub-examples-check:
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/examples/examples.pro ) && $(MAKE) -f Makefile check
check: sub-components-check sub-examples-check

sub-components-benchmark:
	@test -d components/ || mkdir -p components/
	cd components/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/components/components.pro ) && $(MAKE) -f Makefile benchmark
sub-examples-benchmark:
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/examples/examples.pro ) && $(MAKE) -f Makefile benchmark
benchmark: sub-components-benchmark sub-examples-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

.SUFFIXES:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-components-distdir sub-examples-distdir FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents .qmake.conf qt-material-widgets.pro $(DISTDIR)/

sub-components-distdir: FORCE
	@test -d components/ || mkdir -p components/
	cd components/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/components/components.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/components

sub-examples-distdir: FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/runner/work/qt-material-widgets/qt-material-widgets/examples/examples.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/examples

