set(QTMATERIALWIDGETS_CORE_SOURCES
    materiallib/qtmaterialcheckable.cpp
    materiallib/qtmaterialcheckable_internal.cpp
    materiallib/qtmaterialoverlaywidget.cpp
    materiallib/qtmaterialripple.cpp
    materiallib/qtmaterialrippleoverlay.cpp
    materiallib/qtmaterialstatetransition.cpp
    materiallib/qtmaterialstyle.cpp
    materiallib/qtmaterialtheme.cpp)

set(QTMATERIALWIDGETS_CORE_PRIVATE_HEADERS
    materiallib/qtmaterialcheckable_internal.h
    materiallib/qtmaterialcheckable_p.h
    materiallib/qtmaterialstyle_p.h
    materiallib/qtmaterialtheme_p.h)

set(QTMATERIALWIDGETS_WIDGET_SOURCES
    qtmaterialappbar.cpp
    qtmaterialautocomplete.cpp
    qtmaterialautocomplete_internal.cpp
    qtmaterialavatar.cpp
    qtmaterialbadge.cpp
    qtmaterialcheckbox.cpp
    qtmaterialcircularprogress.cpp
    qtmaterialcircularprogress_internal.cpp
    qtmaterialcombobox.cpp
    qtmaterialcombobox_internal.cpp
    qtmaterialdialog.cpp
    qtmaterialdialog_internal.cpp
    qtmaterialdivider.cpp
    qtmaterialdrawer.cpp
    qtmaterialdrawer_internal.cpp
    qtmaterialfab.cpp
    qtmaterialflatbutton.cpp
    qtmaterialflatbutton_internal.cpp
    qtmaterialiconbutton.cpp
    qtmateriallist.cpp
    qtmateriallistitem.cpp
    qtmaterialmenu.cpp
    qtmaterialpaper.cpp
    qtmaterialprogress.cpp
    qtmaterialprogress_internal.cpp
    qtmaterialradiobutton.cpp
    qtmaterialraisedbutton.cpp
    qtmaterialscrollbar.cpp
    qtmaterialscrollbar_internal.cpp
    qtmaterialslider.cpp
    qtmaterialslider_internal.cpp
    qtmaterialsnackbar.cpp
    qtmaterialsnackbar_internal.cpp
    qtmaterialsteps.cpp
    qtmaterialtable.cpp
    qtmaterialtabs.cpp
    qtmaterialtabs_internal.cpp
    qtmaterialtextfield.cpp
    qtmaterialtextfield_internal.cpp
    qtmaterialtoggle.cpp
    qtmaterialtoggle_internal.cpp)

set(QTMATERIALWIDGETS_WIDGET_PRIVATE_HEADERS
    qtmaterialappbar_p.h
    qtmaterialautocomplete_internal.h
    qtmaterialautocomplete_p.h
    qtmaterialavatar_p.h
    qtmaterialbadge_p.h
    qtmaterialcheckbox_p.h
    qtmaterialcircularprogress_internal.h
    qtmaterialcircularprogress_p.h
    qtmaterialcombobox_internal.h
    qtmaterialcombobox_p.h
    qtmaterialdialog_internal.h
    qtmaterialdialog_p.h
    qtmaterialdivider_p.h
    qtmaterialdrawer_internal.h
    qtmaterialdrawer_p.h
    qtmaterialfab_p.h
    qtmaterialflatbutton_internal.h
    qtmaterialflatbutton_p.h
    qtmaterialiconbutton_p.h
    qtmateriallist_p.h
    qtmateriallistitem_p.h
    qtmaterialpaper_p.h
    qtmaterialprogress_internal.h
    qtmaterialprogress_p.h
    qtmaterialradiobutton_p.h
    qtmaterialraisedbutton_p.h
    qtmaterialscrollbar_internal.h
    qtmaterialscrollbar_p.h
    qtmaterialslider_internal.h
    qtmaterialslider_p.h
    qtmaterialsnackbar_internal.h
    qtmaterialsnackbar_p.h
    qtmaterialsteps_p.h
    qtmaterialtable_p.h
    qtmaterialtabs_internal.h
    qtmaterialtabs_p.h
    qtmaterialtextfield_internal.h
    qtmaterialtextfield_p.h
    qtmaterialtoggle_internal.h
    qtmaterialtoggle_p.h)

set(QTMATERIALWIDGETS_PUBLIC_HEADERS
    ../include/qmetarial/components_global.h
    ../include/qmetarial/qtmaterialappbar.h
    ../include/qmetarial/qtmaterialautocomplete.h
    ../include/qmetarial/qtmaterialavatar.h
    ../include/qmetarial/qtmaterialbadge.h
    ../include/qmetarial/qtmaterialcheckbox.h
    ../include/qmetarial/qtmaterialcircularprogress.h
    ../include/qmetarial/qtmaterialcombobox.h
    ../include/qmetarial/qtmaterialdialog.h
    ../include/qmetarial/qtmaterialdivider.h
    ../include/qmetarial/qtmaterialdrawer.h
    ../include/qmetarial/qtmaterialfab.h
    ../include/qmetarial/qtmaterialflatbutton.h
    ../include/qmetarial/qtmaterialiconbutton.h
    ../include/qmetarial/qtmateriallist.h
    ../include/qmetarial/qtmateriallistitem.h
    ../include/qmetarial/qtmaterialmenu.h
    ../include/qmetarial/qtmaterialpaper.h
    ../include/qmetarial/qtmaterialprogress.h
    ../include/qmetarial/qtmaterialradiobutton.h
    ../include/qmetarial/qtmaterialraisedbutton.h
    ../include/qmetarial/qtmaterialscrollbar.h
    ../include/qmetarial/qtmaterialslider.h
    ../include/qmetarial/qtmaterialsnackbar.h
    ../include/qmetarial/qtmaterialsteps.h
    ../include/qmetarial/qtmaterialtable.h
    ../include/qmetarial/qtmaterialtabs.h
    ../include/qmetarial/qtmaterialtextfield.h
    ../include/qmetarial/qtmaterialtoggle.h)

set(QTMATERIALWIDGETS_PUBLIC_LIB_HEADERS
    ../include/qmetarial/lib/qtmaterialcheckable.h
    ../include/qmetarial/lib/qtmaterialoverlaywidget.h
    ../include/qmetarial/lib/qtmaterialripple.h
    ../include/qmetarial/lib/qtmaterialrippleoverlay.h
    ../include/qmetarial/lib/qtmaterialstatetransition.h
    ../include/qmetarial/lib/qtmaterialstatetransitionevent.h
    ../include/qmetarial/lib/qtmaterialstyle.h
    ../include/qmetarial/lib/qtmaterialtheme.h)
