set(QTMATERIALWIDGETS_EXAMPLE_SOURCES
    appbarsettingseditor.cpp
    autocompletesettingseditor.cpp
    avatarsettingseditor.cpp
    badgesettingseditor.cpp
    checkboxsettingseditor.cpp
    circularprogresssettingseditor.cpp
    comboboxsettingseditor.cpp
    demopageregistry.cpp
    dialogsettingseditor.cpp
    dividersettingseditor.cpp
    drawersettingseditor.cpp
    fabsettingseditor.cpp
    flatbuttonsettingseditor.cpp
    iconbuttonsettingseditor.cpp
    main.cpp
    mainwindow.cpp
    menusettingseditor.cpp
    progresssettingseditor.cpp
    radiobuttonsettingseditor.cpp
    raisedbuttonsettingseditor.cpp
    scrollbarsettingseditor.cpp
    slidersettingseditor.cpp
    snackbarsettingseditor.cpp
    stepssettingseditor.cpp
    tabssettingseditor.cpp
    textfieldsettingseditor.cpp
    togglesettingseditor.cpp)

set(QTMATERIALWIDGETS_EXAMPLE_HEADERS
    appbarsettingseditor.h
    autocompletesettingseditor.h
    avatarsettingseditor.h
    badgesettingseditor.h
    checkboxsettingseditor.h
    circularprogresssettingseditor.h
    comboboxsettingseditor.h
    demopageregistry.h
    dialogsettingseditor.h
    dividersettingseditor.h
    drawersettingseditor.h
    fabsettingseditor.h
    flatbuttonsettingseditor.h
    iconbuttonsettingseditor.h
    mainwindow.h
    menusettingseditor.h
    progresssettingseditor.h
    radiobuttonsettingseditor.h
    raisedbuttonsettingseditor.h
    scrollbarsettingseditor.h
    slidersettingseditor.h
    snackbarsettingseditor.h
    stepssettingseditor.h
    tabssettingseditor.h
    textfieldsettingseditor.h
    togglesettingseditor.h)

set(QTMATERIALWIDGETS_EXAMPLE_UI
    appbarsettingsform.ui
    avatarsettingsform.ui
    badgesettingsform.ui
    checkboxsettingsform.ui
    circularprogresssettingsform.ui
    comboboxsettingsform.ui
    dialogsettingsform.ui
    drawersettingsform.ui
    fabsettingsform.ui
    flatbuttonsettingsform.ui
    iconbuttonsettingsform.ui
    progresssettingsform.ui
    radiobuttonsettingsform.ui
    scrollbarsettingsform.ui
    slidersettingsform.ui
    snackbarsettingsform.ui
    stepssettingsform.ui
    tabssettingsform.ui
    textfieldsettingsform.ui
    togglesettingsform.ui)
