#ifndef COMPONENTS_GLOBAL_H
#define COMPONENTS_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(QTMATERIALWIDGETS_LIBRARY)
#  define QTMATERIALWIDGETS_EXPORT Q_DECL_EXPORT
#else
#  define QTMATERIALWIDGETS_EXPORT Q_DECL_IMPORT
#endif

#define COMPONENTS_EXPORT QTMATERIALWIDGETS_EXPORT

#endif  // COMPONENTS_GLOBAL_H
